#include "xcall_generator.h"

#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <unordered_map>

namespace metaffi::compiler::cpp {

// ---------------------------------------------------------------------------
// Static type tables
// ---------------------------------------------------------------------------

namespace {

struct TypeInfo {
    const char* native_cpp;      // C++ scalar type (e.g. "int64_t")
    const char* cdt_field_name;  // union field in cdt_types (e.g. "int64_val")
    const char* metaffi_const;   // MetaFFI type constant (e.g. "metaffi_int64_type")
};

const std::unordered_map<std::string, TypeInfo> kTypeTable = {
    {"int8",    {"int8_t",    "int8_val",    "metaffi_int8_type"}},
    {"int16",   {"int16_t",   "int16_val",   "metaffi_int16_type"}},
    {"int32",   {"int32_t",   "int32_val",   "metaffi_int32_type"}},
    {"int64",   {"int64_t",   "int64_val",   "metaffi_int64_type"}},
    {"uint8",   {"uint8_t",   "uint8_val",   "metaffi_uint8_type"}},
    {"uint16",  {"uint16_t",  "uint16_val",  "metaffi_uint16_type"}},
    {"uint32",  {"uint32_t",  "uint32_val",  "metaffi_uint32_type"}},
    {"uint64",  {"uint64_t",  "uint64_val",  "metaffi_uint64_type"}},
    {"float32", {"float",     "float32_val", "metaffi_float32_type"}},
    {"float64", {"double",    "float64_val", "metaffi_float64_type"}},
    {"bool",    {"uint8_t",   "bool_val",    "metaffi_bool_type"}},
    {"string8", {"char8_t*",  "string8_val", "metaffi_string8_type"}},
    {"handle",  {"void*",     "handle_val",  "metaffi_handle_type"}},
};

std::string strip_array_suffix(const std::string& t) {
    const std::string suf = "_array";
    if (t.size() > suf.size() &&
        t.compare(t.size() - suf.size(), suf.size(), suf) == 0) {
        return t.substr(0, t.size() - suf.size());
    }
    return t;
}

} // namespace

// ---------------------------------------------------------------------------
// Static helpers
// ---------------------------------------------------------------------------

std::string CppXcallGenerator::to_ident(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        out += (std::isalnum(static_cast<unsigned char>(c)) || c == '_') ? c : '_';
    }
    return out;
}

std::string CppXcallGenerator::entrypoint_name(const std::string& class_name,
                                                const std::string& entity_name,
                                                int overload_index) {
    std::string name = "__metaffi__";
    if (!class_name.empty()) {
        name += to_ident(class_name) + "__";
    }
    name += to_ident(entity_name);
    if (overload_index > 0) {
        name += "_" + std::to_string(overload_index);
    }
    return name;
}

std::string CppXcallGenerator::native_type(const metaffi::idl::ArgDefinition& arg) {
    // Use type_alias if the IDL plugin filled it in
    if (!arg.type_alias().empty()) return arg.type_alias();

    const std::string base = strip_array_suffix(arg.type());
    auto it = kTypeTable.find(base);
    if (it == kTypeTable.end()) return "void*"; // opaque fallback
    return it->second.native_cpp;
}

std::string CppXcallGenerator::cdt_field(const std::string& idl_type) {
    const std::string base = strip_array_suffix(idl_type);
    auto it = kTypeTable.find(base);
    if (it == kTypeTable.end()) return "int64_val"; // fallback
    return it->second.cdt_field_name;
}

std::string CppXcallGenerator::metaffi_type_const(const std::string& idl_type) {
    const std::string base = strip_array_suffix(idl_type);
    auto it = kTypeTable.find(base);
    if (it == kTypeTable.end()) return "metaffi_handle_type"; // fallback
    return it->second.metaffi_const;
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

std::string CppXcallGenerator::generate(const metaffi::idl::IDLDefinition& idl,
                                         const std::string& orig_lib) const {
    std::ostringstream out;
    emit_prologue(out, orig_lib);

    for (const auto& module : idl.modules()) {
        emit_module(out, module);
    }

    return out.str();
}

// ---------------------------------------------------------------------------
// Prologue: includes + dlopen/LoadLibrary init
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_prologue(std::ostringstream& out,
                                       const std::string& orig_lib) const {
    out << "// Generated by MetaFFI C++ guest compiler. DO NOT EDIT.\n"
        << "#include <cstdint>\n"
        << "#include <cstdlib>\n"
        << "#include <cstring>\n"
        << "#include <stdexcept>\n"
        << "#include <string>\n"
        << "#include <runtime/cdt.h>\n"
        << "\n"
        << "#ifdef _WIN32\n"
        << "#  define WIN32_LEAN_AND_MEAN\n"
        << "#  include <windows.h>\n"
        << "#  define OPEN_LIB(path)   LoadLibraryA(path)\n"
        << "#  define GET_SYM(h, sym)  GetProcAddress((HMODULE)(h), sym)\n"
        << "#  define CLOSE_LIB(h)     FreeLibrary((HMODULE)(h))\n"
        << "#  define XCALL_EXPORT     extern \"C\" __declspec(dllexport)\n"
        << "#else\n"
        << "#  include <dlfcn.h>\n"
        << "#  define OPEN_LIB(path)   dlopen(path, RTLD_LAZY | RTLD_LOCAL)\n"
        << "#  define GET_SYM(h, sym)  dlsym(h, sym)\n"
        << "#  define CLOSE_LIB(h)     dlclose(h)\n"
        << "#  define XCALL_EXPORT     extern \"C\" __attribute__((visibility(\"default\")))\n"
        << "#endif\n"
        << "\n"
        << "// Path to the original library embedded at code-generation time.\n"
        << "static const char* g_orig_lib_path = \"" << orig_lib << "\";\n"
        << "static void* g_lib_handle = nullptr;\n"
        << "\n"
        << "// Lazy-load the original library; ctx overrides the embedded path.\n"
        << "static void init_lib(void* ctx) {\n"
        << "    if (g_lib_handle) return;\n"
        << "    const char* path = ctx ? static_cast<const char*>(ctx) : g_orig_lib_path;\n"
        << "    g_lib_handle = OPEN_LIB(path);\n"
        << "    if (!g_lib_handle) {\n"
        << "        throw std::runtime_error(std::string(\"guest_xcall: cannot load '\") + path + \"'\");\n"
        << "    }\n"
        << "}\n"
        << "\n"
        << "// Helper: set error string (allocates with malloc).\n"
        << "static void set_xcall_err(char** err, const char* msg) {\n"
        << "    if (!err) return;\n"
        << "    const size_t n = strlen(msg) + 1;\n"
        << "    *err = static_cast<char*>(malloc(n));\n"
        << "    if (*err) memcpy(*err, msg, n);\n"
        << "}\n"
        << "\n"
        << "// Helper: pack a string8 return value into a cdt (heap-allocated copy).\n"
        << "static void pack_string8(struct cdt& c, const char* s) {\n"
        << "    c.type = metaffi_string8_type;\n"
        << "    if (s) {\n"
        << "        const size_t n = strlen(s) + 1;\n"
        << "        c.cdt_val.string8_val = static_cast<char8_t*>(malloc(n));\n"
        << "        if (c.cdt_val.string8_val) memcpy(c.cdt_val.string8_val, s, n);\n"
        << "        c.free_required = 1;\n"
        << "    } else {\n"
        << "        c.cdt_val.string8_val = nullptr;\n"
        << "        c.free_required = 0;\n"
        << "    }\n"
        << "}\n"
        << "\n";
}

// ---------------------------------------------------------------------------
// Per-module emission
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_module(std::ostringstream& out,
                                     const metaffi::idl::ModuleDefinition& module) const {
    out << "// ===== Module: " << module.name() << " =====\n\n";

    // Free functions
    for (const auto& func : module.functions()) {
        emit_free_function(out, func);
    }

    // Classes
    for (const auto& cls : module.classes()) {
        emit_class(out, cls);
    }

    // Globals
    for (const auto& global : module.globals()) {
        emit_global(out, global);
    }
}

// ---------------------------------------------------------------------------
// Free function emission
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_free_function(std::ostringstream& out,
                                             const metaffi::idl::FunctionDefinition& func) const {
    const bool has_params = !func.parameters().empty();
    const bool has_rets   = !func.return_values().empty();
    const std::string ep  = entrypoint_name("", func.name(), func.overload_index());

    // Static function pointer
    out << "// --- " << func.name() << " ---\n";

    // Build pointer typedef and static storage
    if (!has_params && !has_rets) {
        // void(void)
        out << "static void (*g_" << to_ident(func.name()) << ")(void) = nullptr;\n";
    } else {
        // Build argument list for function pointer
        std::string fptr_args;
        for (size_t i = 0; i < func.parameters().size(); ++i) {
            if (i > 0) fptr_args += ", ";
            fptr_args += native_type(func.parameters()[i]);
        }
        std::string ret_type = "void";
        if (has_rets) {
            ret_type = native_type(func.return_values()[0]);
        }
        out << "static " << ret_type << " (*g_" << to_ident(func.name())
            << ")(" << fptr_args << ") = nullptr;\n";
    }

    // Xcall entrypoint
    if (!has_params && !has_rets) {
        // Simplified signature: void(void*, char**)
        out << "XCALL_EXPORT void " << ep << "(void* ctx, char** err) {\n"
            << "    try {\n"
            << "        init_lib(ctx);\n"
            << "        if (!g_" << to_ident(func.name()) << ") {\n"
            << "            g_" << to_ident(func.name())
            << " = (void(*)(void))GET_SYM(g_lib_handle, \"" << func.name() << "\");\n"
            << "        }\n"
            << "        g_" << to_ident(func.name()) << "();\n"
            << "        if (err) *err = nullptr;\n"
            << "    } catch (const std::exception& e) {\n"
            << "        set_xcall_err(err, e.what());\n"
            << "    }\n"
            << "}\n\n";
    } else {
        // Full signature: void(void*, struct cdts*, char**)
        out << "XCALL_EXPORT void " << ep
            << "(void* ctx, struct cdts* params_ret, char** err) {\n"
            << "    try {\n"
            << "        init_lib(ctx);\n"
            << "        if (!g_" << to_ident(func.name()) << ") {\n"
            << "            g_" << to_ident(func.name())
            << " = reinterpret_cast<decltype(g_" << to_ident(func.name())
            << ")>(GET_SYM(g_lib_handle, \"" << func.name() << "\"));\n"
            << "        }\n";

        // Unpack params
        emit_unpack_params(out, func.parameters());

        // Call
        if (has_rets) {
            out << "        auto _ret0 = g_" << to_ident(func.name()) << "(";
        } else {
            out << "        g_" << to_ident(func.name()) << "(";
        }
        for (size_t i = 0; i < func.parameters().size(); ++i) {
            if (i > 0) out << ", ";
            out << "_p" << i;
        }
        out << ");\n";

        // Pack returns
        emit_pack_returns(out, func.return_values());

        out << "        if (err) *err = nullptr;\n"
            << "    } catch (const std::exception& e) {\n"
            << "        set_xcall_err(err, e.what());\n"
            << "    }\n"
            << "}\n\n";
    }
}

// ---------------------------------------------------------------------------
// Class emission
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_class(std::ostringstream& out,
                                    const metaffi::idl::ClassDefinition& cls) const {
    out << "// ===== Class: " << cls.name() << " =====\n\n";

    // Constructors
    for (size_t i = 0; i < cls.constructors().size(); ++i) {
        const auto& ctor = cls.constructors()[i];
        const std::string ep = entrypoint_name(cls.name(), "ctor",
                                               static_cast<int>(i > 0 ? i : 0));

        out << "XCALL_EXPORT void " << ep
            << "(void* ctx, struct cdts* params_ret, char** err) {\n"
            << "    // TODO: construct " << cls.name() << " and store handle\n"
            << "    if (err) *err = nullptr;\n"
            << "}\n\n";
    }

    // Methods
    for (const auto& method : cls.methods()) {
        const std::string ep = entrypoint_name(cls.name(), method.name(),
                                               method.overload_index());
        const bool has_params = !method.parameters().empty();
        const bool has_rets   = !method.return_values().empty();

        if (!has_params && !has_rets) {
            out << "XCALL_EXPORT void " << ep << "(void* ctx, char** err) {\n";
        } else {
            out << "XCALL_EXPORT void " << ep
                << "(void* ctx, struct cdts* params_ret, char** err) {\n";
        }
        out << "    // TODO: dispatch to " << cls.name() << "::" << method.name() << "\n"
            << "    if (err) *err = nullptr;\n"
            << "}\n\n";
    }

    // Destructor / release
    if (cls.release()) {
        const std::string ep = entrypoint_name(cls.name(), "release");
        out << "XCALL_EXPORT void " << ep << "(void* ctx, char** err) {\n"
            << "    // TODO: destroy " << cls.name() << " instance\n"
            << "    if (err) *err = nullptr;\n"
            << "}\n\n";
    }
}

// ---------------------------------------------------------------------------
// Global emission
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_global(std::ostringstream& out,
                                     const metaffi::idl::GlobalDefinition& global) const {
    out << "// ===== Global: " << global.name() << " =====\n\n";

    // Getter
    if (global.getter()) {
        const std::string ep = entrypoint_name("", global.getter()->name());
        out << "XCALL_EXPORT void " << ep
            << "(void* ctx, struct cdts* params_ret, char** err) {\n"
            << "    try {\n"
            << "        init_lib(ctx);\n"
            << "        // TODO: read global " << global.name() << " and pack into params_ret[1]\n"
            << "        if (err) *err = nullptr;\n"
            << "    } catch (const std::exception& e) {\n"
            << "        set_xcall_err(err, e.what());\n"
            << "    }\n"
            << "}\n\n";
    }

    // Setter
    if (global.setter()) {
        const std::string ep = entrypoint_name("", global.setter()->name());
        out << "XCALL_EXPORT void " << ep
            << "(void* ctx, struct cdts* params_ret, char** err) {\n"
            << "    try {\n"
            << "        init_lib(ctx);\n"
            << "        // TODO: unpack params_ret[0] and write global " << global.name() << "\n"
            << "        if (err) *err = nullptr;\n"
            << "    } catch (const std::exception& e) {\n"
            << "        set_xcall_err(err, e.what());\n"
            << "    }\n"
            << "}\n\n";
    }
}

// ---------------------------------------------------------------------------
// CDT marshal helpers
// ---------------------------------------------------------------------------

void CppXcallGenerator::emit_unpack_params(
        std::ostringstream& out,
        const std::vector<metaffi::idl::ArgDefinition>& params) const {

    for (size_t i = 0; i < params.size(); ++i) {
        const auto& p = params[i];
        const std::string base = strip_array_suffix(p.type());
        const bool is_string = (base == "string8" || base == "string16" || base == "string32");

        if (is_string) {
            // Strings are char8_t* in the CDT; convert to std::string for native call
            out << "        std::string _p" << i << ";\n"
                << "        if (params_ret[0].arr[" << i << "].cdt_val.string8_val) {\n"
                << "            _p" << i << " = reinterpret_cast<const char*>(\n"
                << "                params_ret[0].arr[" << i << "].cdt_val.string8_val);\n"
                << "        }\n";
        } else if (p.is_array()) {
            // Packed or CDTS array — emit a placeholder comment; full handling
            // requires knowledge of element type and packing convention.
            out << "        // TODO: unpack array param " << p.name() << " from params_ret[0].arr[" << i << "]\n"
                << "        (void)params_ret;\n";
        } else {
            out << "        auto _p" << i << " = static_cast<" << native_type(p) << ">(\n"
                << "            params_ret[0].arr[" << i << "].cdt_val." << cdt_field(p.type()) << ");\n";
        }
    }
}

void CppXcallGenerator::emit_pack_returns(
        std::ostringstream& out,
        const std::vector<metaffi::idl::ArgDefinition>& rets) const {

    for (size_t i = 0; i < rets.size(); ++i) {
        const auto& r = rets[i];
        const std::string base = strip_array_suffix(r.type());
        const bool is_string = (base == "string8" || base == "string16" || base == "string32");

        // Local variable name — first return uses _ret0, others _ret<i>
        const std::string local = (i == 0) ? "_ret0" : "_ret" + std::to_string(i);

        if (is_string) {
            out << "        pack_string8(params_ret[1].arr[" << i << "], " << local << ".c_str());\n";
        } else if (r.is_array()) {
            out << "        // TODO: pack array return " << r.name()
                << " into params_ret[1].arr[" << i << "]\n";
        } else {
            out << "        params_ret[1].arr[" << i << "].type = " << metaffi_type_const(r.type()) << ";\n"
                << "        params_ret[1].arr[" << i << "].cdt_val." << cdt_field(r.type())
                << " = static_cast<" << native_type(r) << ">(" << local << ");\n";
        }
    }
}

// ---------------------------------------------------------------------------
// Compile command printer
// ---------------------------------------------------------------------------

void CppXcallGenerator::print_compile_commands(const std::string& stem) {
    std::cout << "\n"
              << "// =================================================================\n"
              << "// Compile commands for " << stem << ".cpp\n"
              << "// =================================================================\n"
              << "\n"
              << "// Windows (cl.exe):\n"
              << "//   cl /LD /EHsc " << stem << ".cpp"
              << " /I%METAFFI_HOME%\\include /link /OUT:" << stem << ".dll\n"
              << "\n"
              << "// Linux (g++):\n"
              << "//   g++ -shared -fPIC -o " << stem << ".so " << stem << ".cpp \\\n"
              << "//       -I$METAFFI_HOME/include -Wl,-rpath,$ORIGIN\n"
              << "\n"
              << "// macOS (clang++):\n"
              << "//   clang++ -shared -fPIC -o " << stem << ".dylib " << stem << ".cpp \\\n"
              << "//       -I$METAFFI_HOME/include\n"
              << "\n";
}

} // namespace metaffi::compiler::cpp
