#include "code_generator.h"
#include "type_mapper.h"

#include <algorithm>
#include <sstream>
#include <stdexcept>

namespace metaffi::compiler::cpp {

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

CppCodeGenerator::GeneratedFiles
CppCodeGenerator::generate(const metaffi::idl::IDLDefinition& idl,
                           const std::string& output_filename_stem) const {
    std::ostringstream header;
    std::ostringstream source;

    // --- Header file prologue ---
    header << "#pragma once\n"
           << "// Generated by MetaFFI C++ host compiler. DO NOT EDIT.\n"
           << "#include <metaffi/api/metaffi_api.h>\n"
           << "#include <cstdint>\n"
           << "#include <string>\n"
           << "#include <vector>\n"
           << "#include <tuple>\n"
           << "\n";

    // --- Source file prologue ---
    source << "// Generated by MetaFFI C++ host compiler. DO NOT EDIT.\n"
           << "#include \"" << output_filename_stem << ".hpp\"\n"
           << "#include <memory>\n"
           << "#include <stdexcept>\n"
           << "\n"
           << "using namespace metaffi::api;\n"
           << "\n";

    // --- Emit one block per module ---
    for (const auto& module : idl.modules()) {
        generate_module_header(header, module);
        generate_module_source(source, module, output_filename_stem, idl);
    }

    return {header.str(), source.str()};
}

// ---------------------------------------------------------------------------
// Per-module header generation
// ---------------------------------------------------------------------------

void CppCodeGenerator::generate_module_header(std::ostringstream& out,
                                               const metaffi::idl::ModuleDefinition& module) const {
    const std::string ns = to_ident(module.name()) + "_host";

    out << "namespace " << ns << " {\n"
        << "\n"
        << "// Bind the module before calling any other function.\n"
        << "// module_path: path to the foreign module file.\n"
        << "// runtime_plugin: e.g. \"xllr.python3\"\n"
        << "void bind(const std::string& module_path, const std::string& runtime_plugin);\n"
        << "\n";

    // Free functions declarations
    if (!module.functions().empty()) {
        out << "// --- Free functions ---\n";
        emit_free_function_decls(out, module);
        out << "\n";
    }

    // Global variable accessors
    if (!module.globals().empty()) {
        out << "// --- Globals ---\n";
        emit_global_decls(out, module);
        out << "\n";
    }

    // Class declarations
    if (!module.classes().empty()) {
        out << "// --- Classes ---\n";
        for (const auto& cls : module.classes()) {
            emit_class_decl(out, cls);
            out << "\n";
        }
    }

    out << "} // namespace " << ns << "\n"
        << "\n";
}

void CppCodeGenerator::emit_free_function_decls(std::ostringstream& out,
                                                 const metaffi::idl::ModuleDefinition& module) const {
    for (const auto& func : module.functions()) {
        // Build return type: void or single/tuple return
        const auto& rets = func.return_values();
        std::string ret_type;

        if (rets.empty()) {
            ret_type = "void";
        } else if (rets.size() == 1) {
            ret_type = CppTypeMapper::cpp_type(rets[0].type(), rets[0].dimensions());
        } else {
            // Multiple returns → std::tuple
            std::string inner;
            for (size_t i = 0; i < rets.size(); ++i) {
                if (i > 0) inner += ", ";
                inner += CppTypeMapper::cpp_type(rets[i].type(), rets[i].dimensions());
            }
            ret_type = "std::tuple<" + inner + ">";
        }

        out << ret_type << " " << to_ident(func.name())
            << "(" << params_decl(func.parameters()) << ");\n";
    }
}

void CppCodeGenerator::emit_global_decls(std::ostringstream& out,
                                          const metaffi::idl::ModuleDefinition& module) const {
    for (const auto& global : module.globals()) {
        const std::string cpp_t = CppTypeMapper::cpp_type(global.type(), global.dimensions());

        if (global.getter()) {
            out << cpp_t << " " << to_ident(global.getter()->name()) << "();\n";
        }
        if (global.setter()) {
            out << "void " << to_ident(global.setter()->name())
                << "(" << cpp_t << " v);\n";
        }
    }
}

void CppCodeGenerator::emit_class_decl(std::ostringstream& out,
                                        const metaffi::idl::ClassDefinition& cls) const {
    const std::string class_name = to_ident(cls.name());

    out << "class " << class_name << " {\n"
        << "public:\n";

    // --- Constructors ---
    for (const auto& ctor : cls.constructors()) {
        const auto& params = ctor.parameters();
        if (params.empty()) {
            // Default (no-arg) constructor — calls the entity factory with no arguments
            out << "    " << class_name << "();\n";
        } else {
            out << "    explicit " << class_name
                << "(" << params_decl(params) << ");\n";
        }
    }

    // Wrap-existing-handle constructor (always provided for interop)
    out << "    explicit " << class_name << "(metaffi_handle handle);\n";

    // Destructor
    if (cls.release()) {
        out << "    ~" << class_name << "();\n";
    } else {
        out << "    ~" << class_name << "() = default;\n";
    }

    out << "\n";

    // --- Methods ---
    if (!cls.methods().empty()) {
        out << "    // Methods\n";
        for (const auto& method : cls.methods()) {
            const auto& rets = method.return_values();
            std::string ret_type;

            if (rets.empty()) {
                ret_type = "void";
            } else if (rets.size() == 1) {
                ret_type = CppTypeMapper::cpp_type(rets[0].type(), rets[0].dimensions());
            } else {
                std::string inner;
                for (size_t i = 0; i < rets.size(); ++i) {
                    if (i > 0) inner += ", ";
                    inner += CppTypeMapper::cpp_type(rets[i].type(), rets[i].dimensions());
                }
                ret_type = "std::tuple<" + inner + ">";
            }

            // Filter the implicit instance-handle parameter from the user-visible signature
            const auto user_params = filter_instance_params(method.parameters(), method.instance_required());
            out << "    " << ret_type << " " << to_ident(method.name())
                << "(" << params_decl(user_params) << ");\n";
        }
        out << "\n";
    }

    // --- Field accessors ---
    if (!cls.fields().empty()) {
        out << "    // Field accessors\n";
        for (const auto& field : cls.fields()) {
            const std::string cpp_t = CppTypeMapper::cpp_type(field.type(), field.dimensions());

            if (field.getter()) {
                out << "    " << cpp_t << " " << to_ident(field.getter()->name()) << "() const;\n";
            }
            if (field.setter()) {
                out << "    void " << to_ident(field.setter()->name())
                    << "(" << cpp_t << " v);\n";
            }
        }
        out << "\n";
    }

    out << "private:\n"
        << "    metaffi_handle _handle = nullptr;\n"
        << "    bool _owns_handle = false;\n"
        << "};\n";
}

// ---------------------------------------------------------------------------
// Per-module source generation
// ---------------------------------------------------------------------------

void CppCodeGenerator::generate_module_source(std::ostringstream& out,
                                               const metaffi::idl::ModuleDefinition& module,
                                               const std::string& /*header_stem*/,
                                               const metaffi::idl::IDLDefinition& idl) const {
    const std::string ns = to_ident(module.name()) + "_host";

    out << "namespace " << ns << " {\n"
        << "\n";

    // Static runtime + module handles
    out << "static std::unique_ptr<MetaFFIRuntime> _runtime;\n"
        << "static std::unique_ptr<MetaFFIModule>  _module;\n"
        << "\n";

    // Static entity handles
    emit_entity_statics(out, module);
    out << "\n";

    // bind() implementation
    emit_bind_function(out, module, idl);
    out << "\n";

    // Free function stubs
    emit_free_function_impls(out, module);

    // Global getter/setter stubs
    emit_global_impls(out, module);

    // Class method stubs
    for (const auto& cls : module.classes()) {
        emit_class_impls(out, module, cls);
    }

    out << "} // namespace " << ns << "\n"
        << "\n";
}

void CppCodeGenerator::emit_entity_statics(std::ostringstream& out,
                                            const metaffi::idl::ModuleDefinition& module) const {
    // Free functions
    for (const auto& func : module.functions()) {
        out << "static std::unique_ptr<MetaFFIEntity> " << entity_var("", func.name()) << ";\n";
    }

    // Globals
    for (const auto& global : module.globals()) {
        if (global.getter()) {
            out << "static std::unique_ptr<MetaFFIEntity> " << entity_var("", global.getter()->name()) << ";\n";
        }
        if (global.setter()) {
            out << "static std::unique_ptr<MetaFFIEntity> " << entity_var("", global.setter()->name()) << ";\n";
        }
    }

    // Classes
    for (const auto& cls : module.classes()) {
        const std::string cn = to_ident(cls.name());

        // Constructors
        for (size_t i = 0; i < cls.constructors().size(); ++i) {
            std::string label = "ctor";
            if (cls.constructors().size() > 1) label += "_" + std::to_string(i);
            out << "static std::unique_ptr<MetaFFIEntity> " << entity_var(cn, label) << ";\n";
        }

        // Destructor
        if (cls.release()) {
            out << "static std::unique_ptr<MetaFFIEntity> " << entity_var(cn, "dtor") << ";\n";
        }

        // Methods
        for (const auto& method : cls.methods()) {
            out << "static std::unique_ptr<MetaFFIEntity> " << entity_var(cn, method.name()) << ";\n";
        }

        // Fields
        for (const auto& field : cls.fields()) {
            if (field.getter()) {
                out << "static std::unique_ptr<MetaFFIEntity> " << entity_var(cn, field.getter()->name()) << ";\n";
            }
            if (field.setter()) {
                out << "static std::unique_ptr<MetaFFIEntity> " << entity_var(cn, field.setter()->name()) << ";\n";
            }
        }
    }
}

void CppCodeGenerator::emit_bind_function(std::ostringstream& out,
                                           const metaffi::idl::ModuleDefinition& module,
                                           const metaffi::idl::IDLDefinition& idl) const {
    out << "void bind(const std::string& module_path, const std::string& runtime_plugin) {\n"
        << "    // Load runtime plugin and open module\n"
        << "    _runtime = std::make_unique<MetaFFIRuntime>(runtime_plugin);\n"
        << "    _runtime->load_runtime_plugin();\n"
        << "    _module  = std::make_unique<MetaFFIModule>(_runtime->runtime_plugin(), module_path);\n"
        << "\n";

    // Free functions — use entity_path_as_string to include metaffi_guest_lib
    for (const auto& func : module.functions()) {
        const std::string ep = func.entity_path_as_string(idl);
        out << "    " << entity_var("", func.name())
            << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
            << "        \"" << ep << "\",\n"
            << "        " << type_info_list(func.parameters()) << ",\n"
            << "        " << type_info_list(func.return_values()) << "));\n\n";
    }

    // Globals
    for (const auto& global : module.globals()) {
        if (global.getter()) {
            const std::string ep = global.getter()->entity_path_as_string(idl);
            out << "    " << entity_var("", global.getter()->name())
                << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                << "        \"" << ep << "\",\n"
                << "        " << type_info_list(global.getter()->parameters()) << ",\n"
                << "        " << type_info_list(global.getter()->return_values()) << "));\n\n";
        }
        if (global.setter()) {
            const std::string ep = global.setter()->entity_path_as_string(idl);
            out << "    " << entity_var("", global.setter()->name())
                << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                << "        \"" << ep << "\",\n"
                << "        " << type_info_list(global.setter()->parameters()) << ",\n"
                << "        " << type_info_list(global.setter()->return_values()) << "));\n\n";
        }
    }

    // Classes
    for (const auto& cls : module.classes()) {
        const std::string cn = to_ident(cls.name());

        // Constructors — IDL params list is already correct (no instance handle for ctors)
        for (size_t i = 0; i < cls.constructors().size(); ++i) {
            const auto& ctor = cls.constructors()[i];
            std::string label = "ctor";
            if (cls.constructors().size() > 1) label += "_" + std::to_string(i);

            const std::string ep = ctor.entity_path_as_string(idl);
            out << "    " << entity_var(cn, label)
                << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                << "        \"" << ep << "\",\n"
                << "        " << type_info_list(ctor.parameters()) << ",\n"
                << "        " << type_info_list(ctor.return_values()) << "));\n\n";
        }

        // Destructor
        if (cls.release()) {
            const auto* rel = cls.release();
            const std::string ep = rel->entity_path_as_string(idl);
            out << "    " << entity_var(cn, "dtor")
                << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                << "        \"" << ep << "\",\n"
                << "        " << type_info_list(rel->parameters()) << ",\n"
                << "        {}));\n\n";
        }

        // Methods — IDL params already include the instance handle as first param;
        // use type_info_list directly (no extra handle prepended)
        for (const auto& method : cls.methods()) {
            const std::string ep = method.entity_path_as_string(idl);
            out << "    " << entity_var(cn, method.name())
                << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                << "        \"" << ep << "\",\n"
                << "        " << type_info_list(method.parameters()) << ",\n"
                << "        " << type_info_list(method.return_values()) << "));\n\n";
        }

        // Fields
        for (const auto& field : cls.fields()) {
            if (field.getter()) {
                const std::string ep = field.getter()->entity_path_as_string(idl);
                out << "    " << entity_var(cn, field.getter()->name())
                    << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                    << "        \"" << ep << "\",\n"
                    << "        " << type_info_list(field.getter()->parameters()) << ",\n"
                    << "        " << type_info_list(field.getter()->return_values()) << "));\n\n";
            }
            if (field.setter()) {
                const std::string ep = field.setter()->entity_path_as_string(idl);
                out << "    " << entity_var(cn, field.setter()->name())
                    << " = std::make_unique<MetaFFIEntity>(_module->load_entity_with_info(\n"
                    << "        \"" << ep << "\",\n"
                    << "        " << type_info_list(field.setter()->parameters()) << ",\n"
                    << "        " << type_info_list(field.setter()->return_values()) << "));\n\n";
            }
        }
    }

    out << "}\n";
}

void CppCodeGenerator::emit_free_function_impls(std::ostringstream& out,
                                                  const metaffi::idl::ModuleDefinition& module) const {
    for (const auto& func : module.functions()) {
        const auto& rets = func.return_values();

        // Return type
        std::string ret_type;
        if (rets.empty()) {
            ret_type = "void";
        } else if (rets.size() == 1) {
            ret_type = CppTypeMapper::cpp_type(rets[0].type(), rets[0].dimensions());
        } else {
            std::string inner;
            for (size_t i = 0; i < rets.size(); ++i) {
                if (i > 0) inner += ", ";
                inner += CppTypeMapper::cpp_type(rets[i].type(), rets[i].dimensions());
            }
            ret_type = "std::tuple<" + inner + ">";
        }

        out << ret_type << " " << to_ident(func.name())
            << "(" << params_decl(func.parameters()) << ") {\n";

        out << "    " << call_expression(entity_var("", func.name()),
                                         func.parameters(), rets, false) << "\n";

        out << "}\n\n";
    }
}

void CppCodeGenerator::emit_global_impls(std::ostringstream& out,
                                          const metaffi::idl::ModuleDefinition& module) const {
    for (const auto& global : module.globals()) {
        const std::string cpp_t = CppTypeMapper::cpp_type(global.type(), global.dimensions());

        // Getter
        if (global.getter()) {
            out << cpp_t << " " << to_ident(global.getter()->name()) << "() {\n";

            const std::vector<metaffi::idl::ArgDefinition> no_params;
            out << "    " << call_expression(entity_var("", global.getter()->name()),
                                              no_params, global.getter()->return_values(), false) << "\n";
            out << "}\n\n";
        }

        // Setter
        if (global.setter()) {
            out << "void " << to_ident(global.setter()->name()) << "(" << cpp_t << " v) {\n";

            // Build a single-parameter list with name "v"
            std::vector<metaffi::idl::ArgDefinition> setter_param;
            setter_param.emplace_back("v", global.type(), "", "", global.dimensions());

            const std::vector<metaffi::idl::ArgDefinition> no_rets;
            out << "    " << call_expression(entity_var("", global.setter()->name()),
                                              setter_param, no_rets, false) << "\n";
            out << "}\n\n";
        }
    }
}

void CppCodeGenerator::emit_class_impls(std::ostringstream& out,
                                         const metaffi::idl::ModuleDefinition& /*module*/,
                                         const metaffi::idl::ClassDefinition& cls) const {
    const std::string class_name = to_ident(cls.name());

    // --- Constructors ---
    for (size_t i = 0; i < cls.constructors().size(); ++i) {
        const auto& ctor = cls.constructors()[i];
        const auto& params = ctor.parameters();
        std::string label = "ctor";
        if (cls.constructors().size() > 1) label += "_" + std::to_string(i);

        const auto& rets = ctor.return_values();
        out << class_name << "::" << class_name
            << "(" << params_decl(params) << ") {\n";

        // Call the entity to get the handle.
        // NOTE: We do NOT use call_expression() here because that helper appends
        // "return X;" which is illegal in a constructor.  Emit the call manually.
        if (!rets.empty()) {
            const std::string ret_type = CppTypeMapper::cpp_type(rets[0].type(), rets[0].dimensions());
            const std::string ret_name = to_ident(rets[0].name());
            out << "    auto [" << ret_name << "] = "
                << entity_var(class_name, label)
                << "->call<" << ret_type << ">(";
            if (!params.empty()) {
                out << params_names(params);
            }
            out << ");\n";
            out << "    _handle = " << ret_name << ";\n";
        } else {
            out << "    " << entity_var(class_name, label) << "->call(";
            if (!params.empty()) {
                out << params_names(params);
            }
            out << ");\n";
        }

        out << "    _owns_handle = true;\n"
            << "}\n\n";
    }

    // Handle-wrap constructor (always emitted)
    out << class_name << "::" << class_name << "(metaffi_handle handle)\n"
        << "    : _handle(handle)\n"
        << "    , _owns_handle(false)\n"
        << "{}\n\n";

    // --- Destructor ---
    if (cls.release()) {
        out << class_name << "::~" << class_name << "() {\n"
            << "    // Release foreign object if we own it\n"
            << "    if (_owns_handle && _handle != nullptr) {\n"
            << "        " << entity_var(class_name, "dtor") << "->call(_handle);\n"
            << "        _handle = nullptr;\n"
            << "    }\n"
            << "}\n\n";
    }

    // --- Methods ---
    for (const auto& method : cls.methods()) {
        const auto& rets = method.return_values();

        std::string ret_type;
        if (rets.empty()) {
            ret_type = "void";
        } else if (rets.size() == 1) {
            ret_type = CppTypeMapper::cpp_type(rets[0].type(), rets[0].dimensions());
        } else {
            std::string inner;
            for (size_t i = 0; i < rets.size(); ++i) {
                if (i > 0) inner += ", ";
                inner += CppTypeMapper::cpp_type(rets[i].type(), rets[i].dimensions());
            }
            ret_type = "std::tuple<" + inner + ">";
        }

        // Omit the implicit instance-handle from the user-visible parameter list
        const auto user_params = filter_instance_params(method.parameters(), method.instance_required());

        out << ret_type << " " << class_name << "::" << to_ident(method.name())
            << "(" << params_decl(user_params) << ") {\n";

        out << "    " << call_expression(entity_var(class_name, method.name()),
                                          user_params, rets,
                                          method.instance_required()) << "\n";
        out << "}\n\n";
    }

    // --- Field accessors ---
    for (const auto& field : cls.fields()) {
        const std::string cpp_t = CppTypeMapper::cpp_type(field.type(), field.dimensions());

        // Getter
        if (field.getter()) {
            out << cpp_t << " " << class_name << "::" << to_ident(field.getter()->name())
                << "() const {\n";

            const std::vector<metaffi::idl::ArgDefinition> no_params;
            out << "    " << call_expression(entity_var(class_name, field.getter()->name()),
                                              no_params, field.getter()->return_values(), true) << "\n";
            out << "}\n\n";
        }

        // Setter
        if (field.setter()) {
            out << "void " << class_name << "::" << to_ident(field.setter()->name())
                << "(" << cpp_t << " v) {\n";

            std::vector<metaffi::idl::ArgDefinition> setter_params;
            setter_params.emplace_back("v", field.type(), "", "", field.dimensions());

            const std::vector<metaffi::idl::ArgDefinition> no_rets;
            out << "    " << call_expression(entity_var(class_name, field.setter()->name()),
                                              setter_params, no_rets, true) << "\n";
            out << "}\n\n";
        }
    }
}

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

std::string CppCodeGenerator::params_decl(const std::vector<metaffi::idl::ArgDefinition>& params) const {
    std::string result;

    for (size_t i = 0; i < params.size(); ++i) {
        if (i > 0) result += ", ";
        result += CppTypeMapper::cpp_type(params[i].type(), params[i].dimensions());
        result += " ";
        result += to_ident(params[i].name());
    }

    return result;
}

std::string CppCodeGenerator::params_names(const std::vector<metaffi::idl::ArgDefinition>& params) const {
    std::string result;

    for (size_t i = 0; i < params.size(); ++i) {
        if (i > 0) result += ", ";
        result += to_ident(params[i].name());
    }

    return result;
}

std::string CppCodeGenerator::type_info_list(const std::vector<metaffi::idl::ArgDefinition>& args) const {
    if (args.empty()) {
        return "{}";
    }

    std::string result = "{";
    for (size_t i = 0; i < args.size(); ++i) {
        if (i > 0) result += ", ";
        result += CppTypeMapper::type_info_literal(args[i].type(), args[i].dimensions());
    }
    result += "}";
    return result;
}

std::string CppCodeGenerator::call_expression(const std::string& ev,
                                               const std::vector<metaffi::idl::ArgDefinition>& params,
                                               const std::vector<metaffi::idl::ArgDefinition>& returns,
                                               bool instance_first) const {
    // Build argument string
    std::string args;
    if (instance_first) {
        args = "_handle";
        if (!params.empty()) {
            args += ", " + params_names(params);
        }
    } else {
        args = params_names(params);
    }

    // Build call based on number of return values
    if (returns.empty()) {
        // Void call
        return ev + "->call(" + args + ");";
    }

    if (returns.size() == 1) {
        // Single return — structured binding
        const std::string ret_type = CppTypeMapper::cpp_type(returns[0].type(), returns[0].dimensions());
        const std::string ret_name = to_ident(returns[0].name());
        return "auto [" + ret_name + "] = " + ev + "->call<" + ret_type + ">(" + args + ");\n"
               + "    return " + ret_name + ";";
    }

    // Multiple returns — structured binding + tuple
    std::string binding_names;
    std::string ret_types;
    for (size_t i = 0; i < returns.size(); ++i) {
        if (i > 0) {
            binding_names += ", ";
            ret_types += ", ";
        }
        binding_names += to_ident(returns[i].name());
        ret_types += CppTypeMapper::cpp_type(returns[i].type(), returns[i].dimensions());
    }

    return "auto [" + binding_names + "] = " + ev + "->call<" + ret_types + ">(" + args + ");\n"
           + "    return std::make_tuple(" + binding_names + ");";
}

std::string CppCodeGenerator::entity_var(const std::string& class_name,
                                          const std::string& entity_label) {
    std::string var = "_";
    if (!class_name.empty()) {
        var += to_ident(class_name) + "_";
    }
    var += to_ident(entity_label) + "_entity";
    return var;
}

std::vector<metaffi::idl::ArgDefinition>
CppCodeGenerator::filter_instance_params(const std::vector<metaffi::idl::ArgDefinition>& params,
                                          bool instance_required) {
    // When instance_required is true the IDL always places the handle as the first
    // parameter.  Strip it — the C++ method uses _handle implicitly instead.
    if (!instance_required || params.empty()) {
        return params;
    }
    if (params[0].type() == "handle") {
        return std::vector<metaffi::idl::ArgDefinition>(params.begin() + 1, params.end());
    }
    return params;
}

std::string CppCodeGenerator::to_ident(const std::string& s) {
    std::string result = s;
    // Replace characters not valid in C++ identifiers with underscores
    for (char& c : result) {
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') {
            c = '_';
        }
    }
    return result;
}

} // namespace metaffi::compiler::cpp
