#!/usr/bin/env bash

#set -e

# set metaffi home
echo "export METAFFI_HOME=/opt/metaffi" > /etc/profile.d/metaffi.sh
chmod a+x /etc/profile.d/metaffi.sh
export METAFFI_HOME="/opt/metaffi"

# set symbolic links
ln -s /opt/metaffi/metaffi /usr/bin/metaffi
ln -s /opt/metaffi/libboost_filesystem.so.1.79.0 /usr/lib/libboost_filesystem.so.1.79.0
ln -s /opt/metaffi/libboost_thread.so.1.79.0 /usr/lib/libboost_thread.so.1.79.0

