/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef _DEBUG
#undef _DEBUG
#include <jni.h>
#define _DEBUG
#else
#include <jni.h>
#endif
/* Header for class metaffi_api_accessor_MetaFFIAccessor */

#ifndef _Included_metaffi_api_accessor_MetaFFIAccessor
#define _Included_metaffi_api_accessor_MetaFFIAccessor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    load_runtime_plugin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_load_1runtime_1plugin
		(JNIEnv *, jclass, jstring);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    free_runtime_plugin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_free_1runtime_1plugin
		(JNIEnv *, jclass, jstring);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    load_function
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jlong JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_load_1function
		(JNIEnv *, jclass, jstring, jstring, jstring, jobjectArray, jobjectArray);

 /*
  * Class:     metaffi_api_accessor_MetaFFIAccessor
  * Method:    make_callable
  */
 JNIEXPORT jlong JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_load_1callable
   (JNIEnv *, jclass, jstring, jobject, jstring, jobjectArray, jobjectArray);


/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    free_function
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_free_1function
		(JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    xcall_params_ret
 * Signature: (JLjava/lang/Long;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_xcall_1params_1ret
		(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    xcall_no_params_ret
 * Signature: (JLjava/lang/Long;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_xcall_1no_1params_1ret
		(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    xcall_params_no_ret
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_xcall_1params_1no_1ret
		(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    xcall_no_params_no_ret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_xcall_1no_1params_1no_1ret
		(JNIEnv *, jclass, jlong);


/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    alloc_cdts
 * Signature: (BB)J
 */
JNIEXPORT jlong JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_alloc_1cdts
		(JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    free_cdts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_free_1cdts
		(JNIEnv *, jclass, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    get_pcdt
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_get_1pcdt
		(JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    set_cdt_int64
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_set_1cdt_1int64
		(JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    get_object
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_get_1object
		(JNIEnv *, jclass, jlong);

/*
 * Class:     metaffi_api_accessor_MetaFFIAccessor
 * Method:    remove_object
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_remove_1object
		(JNIEnv *, jclass, jlong);

 /*
  * Class:     metaffi_api_accessor_MetaFFIAccessor
  * Method:    java_to_cdts
  * Signature: (JB[Ljava/lang/Object;[J)J
  */
 JNIEXPORT jlong JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_java_1to_1cdts
   (JNIEnv *, jclass, jlong, jobjectArray, jlongArray);

 /*
  * Class:     metaffi_api_accessor_MetaFFIAccessor
  * Method:    cdts_to_java
  * Signature: (JJ)[Ljava/lang/Object;
  */
 JNIEXPORT jobjectArray JNICALL Java_metaffi_api_accessor_MetaFFIAccessor_cdts_1to_1java
   (JNIEnv *, jclass, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif

